apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fiberplane-daemon.fullname" . }}
  labels:
    {{- include "fiberplane-daemon.labels" . | nindent 4 }}
type: Opaque
data:
  fpd-token: {{ required "fiberplane.fpd_token in values.yaml is required!" .Values.fiberplane.fpd_token | b64enc | quote }}

